export default {
    INTERNAL_SERVER_ERROR_CODE: 500,
    INTERNAL_SERVER_ERROR_MESSAGE: 'Internal Server Error',
    ERROR_CODE: 412,
    ERROR_USER_EXITS: "User Already Exists.",
    BAD_REQUEST_CODE: 400,
    NOT_FOUND_CODE: 404,
    NOT_FOUND_MESSAGE: "Not Found",
    UNAUTHORIZE_CODE: 401,
    UNAUTHORIZE_MESSAGE: "Unthorized Can't Access",
    ERROR: "Something Went Wrong",
    ERROR_NOT_USER: "User Not Found.",
    ERROR_WRONG_PASSWORD: "Please Check Password.",
    SUCCESS_CODE: 200,
    SUCCESS: "Success",
    SUCCESS_USER_INFO: "Get User Infomation",
    SUCCESS_USER_PREF_ADD: "User Preference Added Successfully",
    TOKEN_NOT_PROVIDE: "User Token Not Provided.",
    TOKEN_NOT_EXISTS: "Please Check Authorize Token.",
    TOKEN_UNAUTHORIZED: "Token Was Unauthorized.",
    ERROR_LINK: "Your Link is Expired.",
    ACCOUNT_ACTIVATE: "Your Account is activated.",
    ALREADY_ACTIVE: 'Your account is already Active',
    ACCOUNT_NOT_ACTIVE: 'Your account is not Active'
};